App Setting (Alpha)
myanmarcyberyouths/mCal pull request #93
Opened 2023-11-13 02:24 UTC by YakuBrangJa

# Description
Setting feature to enable more user customizability of the app.

## Type of change
- [*] New feature (non-breaking change which adds functionality)

## Modifications
- Setting model
- General settings
- Moved DarkMode to general setting from navbar

## Note
This is feature is in alpha stage and not recommending merging to the main repo yet. Some of the features are still under implementation.

2023-11-14 02:07 UTC, amm834 requested changes

2023-11-14 02:07 UTC, amm834 commented on apps/myanmar_calendar/src/utils/dateTimeHelper.ts
> +  return index as 0 | 1 | 2 | 3 | 4 | 5 | 6;
You can use type instead of hard coding overtime.

2023-11-14 02:07 UTC, amm834 commented on apps/myanmar_calendar/src/utils/helpers.ts
> +  if (theme === THEME_MODE.system) {
Refactor to the switch statement.

2023-11-14 02:11 UTC, amm834 commented
Could you pls change the camel case to the snake case? 
<img width="769" alt="Screenshot 2023-11-14 at 8 41 16 AM" src="https://github.com/myanmarcyberyouths/mCal/assets/65492233/bc05ac4d-6a67-41fe-a5a0-defcc10b9f99">

2023-11-14 04:54 UTC, YakuBrangJa commented
Thanks for pointing out, I will refactor them.

2023-11-14 04:55 UTC, YakuBrangJa commented
> Could you pls change the camel case to the snake case? <img alt="Screenshot 2023-11-14 at 8 41 16 AM" width="769" src="https://user-images.githubusercontent.com/65492233/282641964-bc05ac4d-6a67-41fe-a5a0-defcc10b9f99.png">

local storage key name or data's object's key names

2023-11-14 05:19 UTC, YakuBrangJa commented on apps/myanmar_calendar/src/components/layouts/Navbar/CalendarSlider.tsx
> +    if (calendarMode === CALENDAR_MODE.WEEK) {
I just realize we can get rid of the conditional statement here.

`      const handleCalendarSlide = (direction: "next" | "prev") => {
    const slideValue = direction === "next" ? 1 : -1;

    dispatch(updateActiveDate({
      [calendarMode + 's']: slideValue
    }))
  };`

2023-11-14 06:32 UTC, amm834 commented
> > Could you pls change the camel case to the snake case? <img alt="Screenshot 2023-11-14 at 8 41 16 AM" width="769" src="https://user-images.githubusercontent.com/65492233/282641964-bc05ac4d-6a67-41fe-a5a0-defcc10b9f99.png">
> 
> local storage key name or object key names

Local storage key name ofc, object name are legal to use as a camel case in the JS codebase, the whole js world follow up with that .

2023-11-15 10:51 UTC, amm834 commented on apps/myanmar_calendar/src/components/layouts/Navbar/CalendarSlider.tsx
> +    if (calendarMode === CALENDAR_MODE.WEEK) {
Ofc, u can remove that

2023-11-27 23:34 UTC, closed without merging